---
name: PART3 - CH1 - Variables 2
on: workflow_dispatch

env:
  GITHUB_ACTOR: "yohan"

jobs:
  build_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "run step1 , say hello to ${{ env.GITHUB_ACTOR }}"
          echo "HELLO TO $GITHUB_ACTOR"
          echo "EVENT: $GITHUB_EVENT_NAME"
      - name: Step 2
        run: |
          echo "job: $GITHUB_JOB"
          echo "Run Id: $GTIHUB_RUN_ID"
      - name: Step 3
        run: |
          echo "variable: ${{ vars.PRODUCTION_SERVER }}"
        
