name: show github action
on: [workflow_dispatch]

env:
  NAME: "github friends"
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: execute first
      run: |
        echo "execute first!!!"
        echo "Branch: ${{ github.actor }}"
    - name: execute second
      run: |
        echo "execute second!!!"
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
    - name: execute third
      run: |
        echo "third job!!!"
        echo "name: $NAME"
