---
  name: PART3 - CH1 - Condition 1
  on: workflow_dispatch
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - if: github.repository == 'jihyungSong/github-action-course'
        name: Step 1
        run: |
          echo "Run Step 1, Say Hello"
      - name: Step 2
        if: github.event_name == 'xxxxxxx'
        run: |
          echo "Run Step 2, Say Hello"
    build2:
      runs-on: ubuntu-latest
      steps:
      -  if: github.event_name == 'worklfow_dispatch'
         name: isWorkflowDispatch
         run: |
           echo "runs on worklfow_dispatch"

     
      
      
